name: Opower Engineering Blog
description: The blog of the Opower engineering team.
url: http://opower.github.io
markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title
exclude: [bin, CONTRIBUTING.md, Gemfile, Gemfile.lock, README.md]
paginate: 5
